import React, { createContext, useContext, useEffect, useState, useMemo, useCallback } from 'react';

export type LanguageCode = 'en' | 'ur' | 'ar';

export interface LanguageContextValue {
  language: LanguageCode;
  isRtl: boolean;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string, defaultText?: string) => string;
}

const STORAGE_KEY = 'allbarka_language';

const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    home: 'Home',
    shop: 'Shop',
    giftBoxes: 'Gift Boxes',
    contact: 'Contact',
    cart: 'Cart',
    vipLogin: 'Patron Login',
    vipPatron: 'VIP Patron',
    menu: 'Menu',
    close: 'Close',
    collections: 'Collections',
    journal: 'Journal',
    account: 'Account',
    orders: 'Orders',
    theme: 'Theme',
    language: 'Language',
    dryFruits: 'Royal Dry Fruits',
    berries: 'Berries & Seeds',
    spices: 'Spices & Saffron',
    combos: 'Gift Combos',
    allProducts: 'All Products',
    storageGuide: 'Cold Storage Guide',
    saffronGuide: 'Kashmiri Saffron Guide',
    giftingEtiquette: 'Gifting Etiquette',
    aboutUs: 'Our Heritage',
    checkout: 'Checkout',
    heroHeadlinePart1: "Nature's finest, delivered with",
    heroHeadlinePart2: 'Pure Elegance',
    heroSubtitle: 'Experience the rich taste of handpicked Iranian pistachios, Chilean walnuts, and roasted cashews. Delivered fresh across Lahore.',
    heroSearchLabel: 'Search luxury dry fruits catalogue',
    searchPlaceholder1: 'Search Iranian Pistachios, Pine Nuts (Chilgoza)...',
    searchPlaceholder2: 'Search Chilean Walnuts & Royal Almonds...',
    searchPlaceholder3: 'Search Bespoke Gift Boxes & Deals...',
    searchPlaceholder4: 'Search Kashmiri Saffron & Medjool Dates...',
    search: 'Search',
    searchPrompt: 'Search dry fruits, saffron, gifts...',
    allBarkaSubtitle: 'LUXURY HARVESTS',
    wholesale: 'Wholesale',
    gifting: 'Luxury Gifting',
    cartEmpty: 'Your Shopping Bag is Empty',
    cartSubtotal: 'Subtotal',
    freeShippingHint: 'Add Rs. {amount} more for Complimentary Courier',
    freeShippingUnlocked: 'Complimentary Courier Unlocked',
    proceedToCheckout: 'Proceed to Checkout',
    continueShopping: 'Continue Shopping',
    filter: 'Filter',
    sort: 'Sort by',
    addToCart: 'Add to Bag',
    price: 'Price',
    quickView: 'Quick View',
    reviewCart: 'Review Cart & Checkout',
    languageSelector: 'Language / زبان / اللغة',
    appearanceMode: 'Appearance Mode',
    patronProfile: 'Patron Profile',
    patronLounge: 'Patron Lounge',
    signInPrompt: 'Sign in for faster checkout',
    shoppingBag: 'Shopping Bag',
    connectWithUs: 'Connect With Us',
    patronAccount: 'Patron Account',
    loyaltyPerks: 'View loyalty perks & tier',
    ourCollections: 'Our Collections',
    inStock: 'In Stock',
    outOfStock: 'Sold Out',
    freshGuarantee: '100% Freshness Guarantee',
    secureCheckout: 'Verified Secure Checkout',
    lahoreConcierge: 'Lahore Concierge',
    connectWhatsapp: 'Connect on WhatsApp',
    newsletterTitle: 'Private Reserve / AllBarka Updates',
    newsletterDesc: 'Receive privileged notices regarding fresh seasonal harvests, wild Skardu arrivals, and exclusive patron privileges.',
    subscribe: 'Subscribe',
    subscribing: 'Submitting...',
    newsletterSuccess: 'Enrolled in AllBarka Private Reserve.',
    footerStory: 'Ethically procured single-origin dry fruits, nuts, and delicacies hand-graded and dispatched fresh daily from Lahore.',
    privacyConsent: 'I agree to receive seasonal harvest drops and private tasting previews.',
    termsNotice: 'Subscribers receive harvest bulletins & festive allocations. Never shared, unsubscribe anytime.',
    allRightsReserved: 'All rights reserved.',
    'imageAlt.pista': 'Shelled pistachios on a cream surface',
    'imageAlt.kaju': 'Whole cashews on a cream surface',
    'imageAlt.badam': 'Whole almonds on a cream surface',
    'imageAlt.akhroot': 'Walnut halves on a cream surface',
    'imageAlt.deal-1': 'Plain packs of walnut halves and pistachios',
    'imageAlt.deal-2': 'Plain packs of almonds and cashews',
    'imageAlt.khubani': 'Dried apricots on a cream surface',
    'imageAlt.alubukhara': 'Dried plums on a cream surface',
    'imageAlt.kishmish': 'Long green raisins on a cream surface',
    'imageAlt.khajoor': 'Dark dates on a cream surface',
    'imageAlt.pumpkin_seeds': 'Raw green pumpkin seeds on a cream surface',
    'imageAlt.chia_seeds': 'Dry chia seeds on a cream surface',
    'imageAlt.nimko': 'Traditional Lahori nimko snack mix',
    'imageAlt.chanay': 'Roasted brown chickpeas on a cream surface',
    'imageAlt.categoryDryFruits': 'Dried fruits arranged in four small bowls',
    'imageAlt.categoryOils': 'Bottle of cold-pressed oil',
    'imageAlt.categoryEssentials': 'Jar of organic desi ghee',
    'imageAlt.categorySnacks': 'Traditional Lahori nimko snack mix',
    'imageAlt.categoryGifts': 'Plain gift packs of walnuts and pistachios',
    'imageAlt.categoryDealBoxes': 'Plain packs of almonds and cashews',
    'imageAlt.hero': 'Dry fruits arranged around a deep emerald surface',
    // Trust badge keys — factual claims only
    'trust.halal': 'Halal Friendly',
    'trust.halalDesc': 'All products are halal-friendly with no prohibited ingredients',
    'trust.natural': 'Natural Ingredients',
    'trust.naturalDesc': 'No artificial colors, flavors, or preservatives',
    'trust.secureCheckout': 'Secure Checkout',
    'trust.secureCheckoutDesc': 'Encrypted payment processing for your safety',
    'trust.cod': 'COD Available',
    'trust.codDesc': 'Pay on delivery — no advance payment required',
    'trust.delivery': 'Pakistan-Wide Delivery',
    'trust.deliveryDesc': 'Shipped to all major cities across Pakistan',
    'trust.fresh': 'Fresh Batch Promise',
    'trust.freshDesc': 'Packed and dispatched fresh from our Lahore facility',
    'trust.authentic': '100% Authentic',
    'trust.authenticDesc': 'Ethically sourced single-origin harvests',
    'trust.fastDelivery': 'Fast Delivery',
    'trust.fastDeliveryDesc': 'Same-day in Lahore, fast nationwide',
    'trust.easyReturns': 'Easy Returns',
    'trust.easyReturnsDesc': 'Hassle-free replacement guarantee',
    // Product detail page
    'weightSelector': 'Select Weight / Portion',
    'quantity': 'Quantity',
    'addToCartPrice': 'Add to Cart',
    'wishlist': 'Wishlist',
    'shareItem': 'Share Item',
    'selectWeight': 'Select Size',
    'tasteProfile': 'Taste Profile',
    'packContents': 'Pack Contents',
    'originLabel': 'Origin',
    'relatedProducts': 'Complementary Gourmet Selections',
    'viewFullHarvest': 'View Full Harvest',
    'viewFullDetails': 'View Full Details',
    'addedToCart': 'Added to Cart',
    'wholesaleQty': 'Wholesale Quantity',
    'verifiedReviews': 'Verified Lahore Patron Feedback',
    'whatCustomersSay': 'What Our Customers Say',
    'conciergeOffline': 'Our concierge is resting. Please reach us on WhatsApp for assistance.',
    'whatsappContact': 'Connect on WhatsApp',
    'typeMessage': 'Type your message...',
    'retry': 'Retry',
    'clearChat': 'Clear Chat',
    'reviewsDesc': 'Continuous feedback from WhatsApp orders and deliveries across Lahore. Hover over any card to pause and read.',
    '100plusReviews': '100+ Lahore Reviews',
    'airtightJars': 'Airtight Resealable Jars',
    'codLahore': 'Cash on Delivery across Lahore',
    'freshnessPromise': 'Our Freshness & Purity Promise',
    'freshnessDesc': 'Every batch is sorted, checked for natural oil freshness, and sealed in airtight packaging before courier dispatch. If any item does not meet your expectations, we offer instant replacement or support.',
    'cleanSorting': 'Clean Sorting',
    'resealableJars': 'Resealable Freshness Jars',
    'directWhatsapp': 'Direct WhatsApp Dispatch',
    // CategoryPLP & ShopPage
    nuts: 'Dry Fruits & Nuts',
    seeds: 'Seeds & Superfoods',
    snacks: 'Premium Snacks',
    oils: 'Cold-Pressed Oils',
    organics: 'Pure Organic Essentials',
    giftingCategory: 'Luxury Gifting',
    wholesaleCategory: 'Wholesale Bulk',
    searchPlaceholder: 'Search dry fruits, saffron, gifts...',
    // Checkout & Totals
    giftWrap: 'Gift Packaging',
    shippingFee: 'Shipping Fee',
    expressShipping: 'Express Shipping',
    standardShipping: 'Standard Shipping',
    totalPayable: 'Total Payable',
    cashOnDelivery: 'Cash on Delivery',
    directBankTransfer: 'Direct Bank Transfer',
    orderSummary: 'Order Summary',
    viewDetails: 'View Details',
    conciergeSupport: 'Concierge Support',
    'hero.rotating.1': 'Royal',
    'hero.rotating.2': 'Pure',
    'hero.rotating.3': 'Premium',
    'stats.customers': 'Happy Customers',
    'stats.products': 'Premium Products',
    'stats.cities': 'Cities Served',
    'stats.years': 'Years of Trust'
  },
  ur: {
    home: 'ہوم',
    shop: 'دکان',
    giftBoxes: 'تحائف اور بکس',
    contact: 'رابطہ',
    cart: 'ٹوکری',
    vipLogin: 'معزز لاگ ان',
    vipPatron: 'معزز سرپرست',
    menu: 'فہرست',
    close: 'بند کریں',
    collections: 'مجموعات',
    journal: 'جریدہ اور مضامین',
    account: 'اکاؤنٹ',
    orders: 'آرڈرز',
    theme: 'تھیم',
    language: 'زبان',
    dryFruits: 'شاہی میوہ جات',
    berries: 'بیریز اور بیج',
    spices: 'خالص زعفران و مصالحہ جات',
    combos: 'گفٹ کمبوز',
    allProducts: 'تمام مصنوعات',
    storageGuide: 'تازگی اور اسٹوریج گائیڈ',
    saffronGuide: 'کشمیری زعفران گائیڈ',
    giftingEtiquette: 'شاہی تحائف کے آداب',
    aboutUs: 'ہماری تاریخ',
    checkout: 'چیک آؤٹ',
    heroHeadlinePart1: 'قدرت کے بہترین شاہی میوہ جات،',
    heroHeadlinePart2: 'خالص نفاست کے ساتھ',
    heroSubtitle: 'ایرانی پستے، چلی کے اخروٹ اور بھنے ہوئے کاجو کا لازوال ذائقہ۔ لاہور بھر میں محفوظ اور تازہ ترسیل۔',
    heroSearchLabel: 'خشک میوہ جات کی فہرست میں تلاش کریں',
    searchPlaceholder1: 'ایرانی پستے، چلغوزہ اور کاجو تلاش کریں...',
    searchPlaceholder2: 'چلی کے اخروٹ اور شاہی بادام تلاش کریں...',
    searchPlaceholder3: 'شاہی گفٹ بکس اور خاص پیکیجز تلاش کریں...',
    searchPlaceholder4: 'کشمیری زعفران اور مدینہ کی عجوہ کھجوریں تلاش کریں...',
    search: 'تلاش کریں',
    searchPrompt: 'خشک میوہ جات، زعفران یا گفٹ باکس تلاش کریں...',
    allBarkaSubtitle: 'شاہی سوغات',
    wholesale: 'تھوک / ہول سیل',
    gifting: 'شاہی تحائف',
    cartEmpty: 'آپ کا شاپنگ بیگ خالی ہے',
    cartSubtotal: 'میزان',
    freeShippingHint: 'مفت ترسیل کے لیے مزید {amount} روپے شامل کریں',
    freeShippingUnlocked: 'مفت ترسیل فعال ہو گئی ہے',
    proceedToCheckout: 'چیک آؤٹ کی طرف بڑھیں',
    continueShopping: 'خریداری جاری رکھیں',
    filter: 'فلٹر کریں',
    sort: 'ترتیب دیں',
    addToCart: 'بیگ میں شامل کریں',
    price: 'قیمت',
    quickView: 'فوری جائزہ',
    reviewCart: 'ٹوکری اور چیک آؤٹ کا جائزہ لیں',
    languageSelector: 'زبان / Language / اللغة',
    appearanceMode: 'ظاہری حالت / تھیم',
    patronProfile: 'معزز پروفائل',
    patronLounge: 'معزز لاؤنج',
    signInPrompt: 'تیز تر چیک آؤٹ کے لیے لاگ ان کریں',
    shoppingBag: 'شاپنگ بیگ',
    connectWithUs: 'ہم سے رابطہ کریں',
    patronAccount: 'معزز اکاؤنٹ',
    loyaltyPerks: 'وفاداری کے فوائد اور درجہ دیکھیں',
    ourCollections: 'ہمارے مجموعے',
    inStock: 'دستیاب ہے',
    outOfStock: 'ختم ہو چکا',
    freshGuarantee: '۱۰۰ فیصد تازگی کی ضمانت',
    secureCheckout: 'محفوظ تصدیق شدہ چیک آؤٹ',
    lahoreConcierge: 'لاہور دربان / کونسیرج',
    connectWhatsapp: 'واٹس ایپ پر رابطہ کریں',
    newsletterTitle: 'شاہی خصوصی خبرنامہ',
    newsletterDesc: 'تازہ فصلوں، گلگت و سکردو کی آمد اور خصوصی پیشکشوں کی پیشگی اطلاع حاصل کریں۔',
    subscribe: 'شامل ہوں',
    subscribing: 'ارسال ہو رہا ہے...',
    newsletterSuccess: 'آپ آل برکہ کے خصوصی ریزرو میں شامل ہو چکے ہیں۔',
    footerStory: 'لاہور سے روزانہ تازہ بھیجے جانے والے خالص، اعلیٰ ترین خشک میوہ جات اور شاہی سوغاتیں۔',
    privacyConsent: 'میں تازہ فصلوں کی آمد اور نجی پیشکشوں سے مطلع رہنے کی توثیق کرتا ہوں۔',
    termsNotice: 'ہم آپ کی معلومات کو محفوظ رکھتے ہیں، کسی بھی وقت رکنیت ختم کر سکتے ہیں۔',
    allRightsReserved: 'جملہ حقوق محفوظ ہیں۔',
    'imageAlt.pista': 'کریم سطح پر چھلے ہوئے پستے',
    'imageAlt.kaju': 'کریم سطح پر ثابت کاجو',
    'imageAlt.badam': 'کریم سطح پر ثابت بادام',
    'imageAlt.akhroot': 'کریم سطح پر اخروٹ کی گری',
    'imageAlt.deal-1': 'اخروٹ اور پستے کے سادہ پیک',
    'imageAlt.deal-2': 'بادام اور کاجو کے سادہ پیک',
    'imageAlt.khubani': 'کریم سطح پر خشک خوبانی',
    'imageAlt.alubukhara': 'کریم سطح پر خشک آلو بخارا',
    'imageAlt.kishmish': 'کریم سطح پر لمبی سبز کشمش',
    'imageAlt.khajoor': 'کریم سطح پر گہری رنگت والی کھجوریں',
    'imageAlt.pumpkin_seeds': 'کریم سطح پر کچے سبز کدو کے بیج',
    'imageAlt.chia_seeds': 'کریم سطح پر خشک چیا کے بیج',
    'imageAlt.nimko': 'روایتی لاہوری نمکو',
    'imageAlt.chanay': 'کریم سطح پر بھنے ہوئے بھورے چنے',
    'imageAlt.categoryDryFruits': 'چار پیالیوں میں سجے خشک میوہ جات',
    'imageAlt.categoryOils': 'خالص تیل کی بوتل',
    'imageAlt.categoryEssentials': 'خالص دیسی گھی کا جار',
    'imageAlt.categorySnacks': 'روایتی لاہوری نمکو',
    'imageAlt.categoryGifts': 'اخروٹ اور پستے کے سادہ تحفہ پیک',
    'imageAlt.categoryDealBoxes': 'بادام اور کاجو کے سادہ پیک',
    'imageAlt.hero': 'گہری زمردی سطح کے کناروں پر سجے خشک میوہ جات',
    // Trust badge keys
    'trust.halal': 'حلال دوست',
    'trust.halalDesc': 'تمام مصنوعات حلال اجزاء سے تیار کی گئی ہیں',
    'trust.natural': 'قدرتی اجزاء',
    'trust.naturalDesc': 'مصنوعی رنگ، ذائقہ، یا محافظ کے بغیر',
    'trust.secureCheckout': 'محفوظ چیک آؤٹ',
    'trust.secureCheckoutDesc': 'خفیہ کاری سے محفوظ ادائیگی',
    'trust.cod': 'بوقت ترسیل ادائیگی',
    'trust.codDesc': 'ڈیلیوری پر ادائیگی — پیشگی رقم کی ضرورت نہیں',
    'trust.delivery': 'پاکستان بھر ترسیل',
    'trust.deliveryDesc': 'پاکستان کے تمام بڑے شہروں میں ترسیل',
    'trust.fresh': 'تازہ بیچ کا وعدہ',
    'trust.freshDesc': 'لاہور میں تازہ پیک اور بھیجا جاتا ہے',
    'trust.authentic': '۱۰۰ فیصد اصلی',
    'trust.authenticDesc': 'اخلاقی طور پر حاصل کی گئی واحد ماخذ کی فصلیں',
    'trust.fastDelivery': 'تیز ترسیل',
    'trust.fastDeliveryDesc': 'لاہور میں اسی دن، ملک بھر میں تیز',
    'trust.easyReturns': 'آسان واپسی',
    'trust.easyReturnsDesc': 'بغیر کسی پریشانی کے تبدیلی کی ضمانت',
    // Product detail
    'weightSelector': 'وزن / مقدار منتخب کریں',
    'quantity': 'تعداد',
    'addToCartPrice': 'ٹوکری میں شامل کریں',
    'wishlist': 'پسندیدہ',
    'shareItem': 'شئیر کریں',
    'selectWeight': 'سائز منتخب کریں',
    'tasteProfile': 'ذائقہ کا خاکہ',
    'packContents': 'پیک کے مشتملات',
    'originLabel': 'ماخذ',
    'relatedProducts': 'ملتے جلتے انتخاب',
    'viewFullHarvest': 'مکمل فہرست دیکھیں',
    'viewFullDetails': 'مکمل تفصیلات دیکھیں',
    'addedToCart': 'ٹوکری میں شامل کر لیا گیا',
    'wholesaleQty': 'تھوک مقدار',
    'verifiedReviews': 'لاہور کے صارفین کی تصدیق شدہ آراء',
    'whatCustomersSay': 'ہمارے گاہک کیا کہتے ہیں',
    'conciergeOffline': 'ہمارا دربان آرام کر رہا ہے۔ براہ کرم مدد کے لیے ہم سے واٹس ایپ پر رابطہ کریں۔',
    'whatsappContact': 'واٹس ایپ پر رابطہ کریں',
    'typeMessage': 'اپنا پیغام ٹائپ کریں...',
    'retry': 'دوبارہ کوشش کریں',
    'clearChat': 'چیٹ صاف کریں',
    'reviewsDesc': 'لاہور بھر میں واٹس ایپ آرڈرز اور ڈیلیوری سے موصول ہونے والی آراء۔ پڑھنے کے لیے کسی بھی کارڈ پر کرسر لے جائیں۔',
    '100plusReviews': 'لاہور کی 100+ آراء',
    'airtightJars': 'ہوا بند (ایئر ٹائٹ) جار',
    'codLahore': 'پورے لاہور میں کیش آن ڈیلیوری',
    'freshnessPromise': 'ہماری تازگی اور خالص پن کی ضمانت',
    'freshnessDesc': 'ہر بیچ کو چھانٹ کر، قدرتی تیل کی تازگی کے لیے چیک کیا جاتا ہے، اور بھیجنے سے پہلے ہوا بند پیکنگ میں سیل کیا جاتا ہے۔ اگر کوئی چیز آپ کی توقعات پر پوری نہ اترے تو ہم فوری تبدیلی یا مدد فراہم کرتے ہیں۔',
    'cleanSorting': 'صاف ستھری چھانٹی',
    'resealableJars': 'دوبارہ سیل ہونے والے جار',
    'directWhatsapp': 'براہ راست واٹس ایپ ترسیل',
    'nuts': 'شاہی میوہ جات اور گری دار میوے',
    'seeds': 'بیج اور غذائی اجزاء',
    'snacks': 'اعلیٰ لاہوری سنیکس',
    'oils': 'کولڈ پریسڈ خالص روغن',
    'organics': 'خالص نامیاتی اشیاء',
    'giftingCategory': 'شاہی تحائف',
    'wholesaleCategory': 'تھوک و ہول سیل',
    'searchPlaceholder': 'خشک میوہ جات، زعفران یا گفٹ باکس تلاش کریں...',
    // Checkout & Totals
    'giftWrap': 'تحفہ پیکنگ',
    'shippingFee': 'ترسیل کا کرایہ',
    'expressShipping': 'تیز ترین ترسیل',
    'standardShipping': 'عام ترسیل',
    'totalPayable': 'کل قابل ادا رقم',
    'cashOnDelivery': 'کیش آن ڈیلیوری',
    'directBankTransfer': 'ڈائریکٹ بینک ٹرانسفر',
    'orderSummary': 'آرڈر کا خلاصہ',
    'viewDetails': 'تفصیلات دیکھیں',
    'conciergeSupport': 'شاہی مدد و دربان',
    'hero.rotating.1': 'شاہی',
    'hero.rotating.2': 'خالص',
    'hero.rotating.3': 'اعلیٰ',
    'stats.customers': 'خوش گاہک',
    'stats.products': 'اعلیٰ مصنوعات',
    'stats.cities': 'شہر جہاں خدمت',
    'stats.years': 'سالوں کا اعتماد'
  },
  ar: {
    home: 'الرئيسية',
    shop: 'المتجر',
    giftBoxes: 'صناديق الهدايا',
    contact: 'اتصل بنا',
    cart: 'السلة',
    vipLogin: 'دخول كبار الشخصيات',
    vipPatron: 'عميل مميز',
    menu: 'القائمة',
    close: 'إغلاق',
    collections: 'المجموعات',
    journal: 'المجلة والقصص',
    account: 'الحساب',
    orders: 'الطلبات',
    theme: 'المظهر',
    language: 'اللغة',
    dryFruits: 'الفواكه المجففة الملكية',
    berries: 'التوت والبذور',
    spices: 'الزعفران والبهارات',
    combos: 'باقات الهدايا',
    allProducts: 'جميع المنتجات',
    storageGuide: 'دليل حفظ النضارة',
    saffronGuide: 'دليل الزعفران الكشميري',
    giftingEtiquette: 'أصول الإهداء الفاخر',
    aboutUs: 'تاريخنا وأصالتنا',
    checkout: 'الدفع',
    heroHeadlinePart1: 'أجود ثمار الطبيعة، بلمسة من',
    heroHeadlinePart2: 'الفخامة الخالصة',
    heroSubtitle: 'تذوق الفستق الإيراني الفاخر والجوز والكاجو المحمص. توصيل طازج وموثوق في جميع أنحاء لاهور.',
    heroSearchLabel: 'ابحث في قائمة الفواكه المجففة الفاخرة',
    searchPlaceholder1: 'ابحث عن الفستق الإيراني، الصنوبر (چلغوزة)...',
    searchPlaceholder2: 'ابحث عن الجوز التشيلي واللوز الملكي...',
    searchPlaceholder3: 'ابحث عن صناديق الهدايا الفاخرة وباقات العروض...',
    searchPlaceholder4: 'ابحث عن الزعفران الكشميري وتمور المجدول...',
    search: 'بحث',
    searchPrompt: 'ابحث عن الفواكه المجففة، الزعفران، الهدايا...',
    allBarkaSubtitle: 'محاصيل فاخرة',
    wholesale: 'بالجملة',
    gifting: 'الهدايا الفاخرة',
    cartEmpty: 'حقيبة التسوق فارغة',
    cartSubtotal: 'المجموع الفرعي',
    freeShippingHint: 'أضف {amount} روبية إضافية للحصول على شحن مجاني',
    freeShippingUnlocked: 'تم تفعيل الشحن المجاني',
    proceedToCheckout: 'متابعة الدفع',
    continueShopping: 'مواصلة التسوق',
    filter: 'تصفية',
    sort: 'ترتيب حسب',
    addToCart: 'أضف إلى السلة',
    price: 'السعر',
    quickView: 'نظرة سريعة',
    reviewCart: 'مراجعة السلة والدفع',
    languageSelector: 'اللغة / Language / زبان',
    appearanceMode: 'وضع المظهر',
    patronProfile: 'ملف العميل المميز',
    patronLounge: 'صالة كبار الشخصيات',
    signInPrompt: 'تسجيل الدخول لإتمام الطلب بشكل أسرع',
    shoppingBag: 'حقيبة التسوق',
    connectWithUs: 'تواصل معنا',
    patronAccount: 'حساب العميل المميز',
    loyaltyPerks: 'عرض مزايا ومستوى العضوية',
    ourCollections: 'مجموعاتنا',
    inStock: 'متوفر',
    outOfStock: 'نفد المخزون',
    freshGuarantee: 'ضمان النضارة ١٠٠٪',
    secureCheckout: 'دفع آمن ومضمون',
    lahoreConcierge: 'خدمة كونسيرج لاهور',
    connectWhatsapp: 'تواصل عبر واتساب',
    newsletterTitle: 'نشرة المحاصيل الخاصة',
    newsletterDesc: 'احصل على إشعارات خاصة بوصول المحاصيل الموسمية الطازجة وعروض الأعضاء الحصرية.',
    subscribe: 'اشتراك',
    subscribing: 'جاري الإرسال...',
    newsletterSuccess: 'تم انضمامك إلى قائمة المحاصيل الخاصة بنجاح.',
    footerStory: 'فواكه مجففة ومكسرات فاخرة مفروزة يدوياً ومغلفة بعناية لتصلكم طازجة يومياً من لاهور.',
    privacyConsent: 'أوافق على استلام تحديثات المحاصيل الموسمية ودعوات التذوق الخاصة.',
    termsNotice: 'بياناتكم سرية ومحفوظة تماماً، يمكنكم إلغاء الاشتراك في أي وقت.',
    allRightsReserved: 'جميع الحقوق محفوظة.',
    'imageAlt.pista': 'فستق مقشر على سطح كريمي',
    'imageAlt.kaju': 'حبوب كاجو كاملة على سطح كريمي',
    'imageAlt.badam': 'حبوب لوز كاملة على سطح كريمي',
    'imageAlt.akhroot': 'أنصاف جوز على سطح كريمي',
    'imageAlt.deal-1': 'عبوات بسيطة من الجوز والفستق',
    'imageAlt.deal-2': 'عبوات بسيطة من اللوز والكاجو',
    'imageAlt.khubani': 'مشمش مجفف على سطح كريمي',
    'imageAlt.alubukhara': 'برقوق مجفف على سطح كريمي',
    'imageAlt.kishmish': 'زبيب أخضر طويل على سطح كريمي',
    'imageAlt.khajoor': 'تمور داكنة على سطح كريمي',
    'imageAlt.pumpkin_seeds': 'بذور يقطين خضراء نيئة على سطح كريمي',
    'imageAlt.chia_seeds': 'بذور شيا جافة على سطح كريمي',
    'imageAlt.nimko': 'مزيج نمكو لاهوري تقليدي',
    'imageAlt.chanay': 'حمص بني محمص على سطح كريمي',
    'imageAlt.categoryDryFruits': 'فواكه مجففة مرتبة في أربعة أوعية صغيرة',
    'imageAlt.categoryOils': 'زجاجة من الزيت المعصور على البارد',
    'imageAlt.categoryEssentials': 'وعاء من السمن العضوي',
    'imageAlt.categorySnacks': 'مزيج نمكو لاهوري تقليدي',
    'imageAlt.categoryGifts': 'عبوات هدايا بسيطة من الجوز والفستق',
    'imageAlt.categoryDealBoxes': 'عبوات بسيطة من اللوز والكاجو',
    'imageAlt.hero': 'فواكه مجففة مرتبة حول سطح زمردي داكن',
    // Trust badge keys
    'trust.halal': 'منتجات حلال',
    'trust.halalDesc': 'جميع المنتجات حلال وخالية من المكونات المحظورة',
    'trust.natural': 'مكونات طبيعية',
    'trust.naturalDesc': 'بدون ألوان أو نكهات أو مواد حافظة صناعية',
    'trust.secureCheckout': 'دفع آمن',
    'trust.secureCheckoutDesc': 'معالجة مدفوعات مشفرة لأمانك',
    'trust.cod': 'الدفع عند الاستلام',
    'trust.codDesc': 'ادفع عند التوصيل — لا يلزم دفع مسبق',
    'trust.delivery': 'توصيل لجميع أنحاء باكستان',
    'trust.deliveryDesc': 'الشحن إلى جميع المدن الرئيسية في باكستان',
    'trust.fresh': 'ضمان الدفعة الطازجة',
    'trust.freshDesc': 'معبأ ومشحون طازجاً من منشأتنا في لاهور',
    'trust.authentic': 'أصلي ١٠٠٪',
    'trust.authenticDesc': 'محاصيل ذات مصدر واحد محصودة أخلاقياً',
    'trust.fastDelivery': 'توصيل سريع',
    'trust.fastDeliveryDesc': 'في نفس اليوم في لاهور، سريع على الصعيد الوطني',
    'trust.easyReturns': 'إرجاع سهل',
    'trust.easyReturnsDesc': 'ضمان استبدال بدون متاعب',
    // Product detail
    'weightSelector': 'اختر الوزن / الكمية',
    'quantity': 'الكمية',
    'addToCartPrice': 'أضف إلى السلة',
    'wishlist': 'المفضلة',
    'shareItem': 'مشاركة',
    'selectWeight': 'اختر الحجم',
    'tasteProfile': 'ملف الطعم',
    'packContents': 'محتويات العبوة',
    'originLabel': 'المصدر',
    'relatedProducts': 'اختيارات ذات صلة',
    'viewFullHarvest': 'عرض المحصول الكامل',
    'viewFullDetails': 'عرض التفاصيل الكاملة',
    'addedToCart': 'تمت الإضافة إلى السلة',
    'wholesaleQty': 'كمية الجملة',
    'verifiedReviews': 'آراء موثقة من عملاء لاهور',
    'whatCustomersSay': 'ماذا يقول عملاؤنا',
    'conciergeOffline': 'الكونسيرج الخاص بنا في فترة راحة. يرجى التواصل معنا عبر واتساب للحصول على المساعدة.',
    'whatsappContact': 'تواصل عبر واتساب',
    'typeMessage': 'اكتب رسالتك...',
    'retry': 'إعادة المحاولة',
    'clearChat': 'مسح المحادثة',
    'reviewsDesc': 'آراء مستمرة من طلبات واتساب والتوصيل في جميع أنحاء لاهور. مرر مؤشر الماوس فوق أي بطاقة للإيقاف المؤقت والقراءة.',
    '100plusReviews': 'أكثر من 100 رأي من لاهور',
    'airtightJars': 'برطمانات محكمة الإغلاق',
    'codLahore': 'الدفع عند الاستلام في جميع أنحاء لاهور',
    'freshnessPromise': 'وعدنا بالنضارة والنقاء',
    'freshnessDesc': 'يتم فرز كل دفعة، والتحقق من نضارة زيتها الطبيعي، وإغلاقها في عبوات محكمة الإغلاق قبل الإرسال. إذا لم يلبِّ أي منتج توقعاتك، فنحن نقدم استبدالاً أو دعماً فورياً.',
    'cleanSorting': 'فرز نظيف',
    'resealableJars': 'برطمانات نضارة قابلة لإعادة الإغلاق',
    'directWhatsapp': 'إرسال مباشر عبر واتساب',
    'nuts': 'الفواكه المجففة والمكسرات',
    'seeds': 'البذور والأغذية الفائقة',
    'snacks': 'المأكولات الخفيفة الفاخرة',
    'oils': 'الزيوت المعصورة على البارد',
    'organics': 'المستلزمات العضوية الخالصة',
    'giftingCategory': 'الهدايا الفاخرة',
    'wholesaleCategory': 'مبيعات الجملة',
    'searchPlaceholder': 'ابحث عن الفواكه المجففة، الزعفران، الهدايا...',
    // Checkout & Totals
    'giftWrap': 'تغليف الهدايا',
    'shippingFee': 'رسوم الشحن',
    'expressShipping': 'الشحن السريع',
    'standardShipping': 'الشحن القياسي',
    'totalPayable': 'إجمالي المبلغ المستحق',
    'cashOnDelivery': 'الدفع عند الاستلام',
    'directBankTransfer': 'تحويل بنكي مباشر',
    'orderSummary': 'ملخص الطلب',
    'viewDetails': 'عرض التفاصيل',
    'conciergeSupport': 'دعم الكونسيرج',
    'hero.rotating.1': 'ملكي',
    'hero.rotating.2': 'خالص',
    'hero.rotating.3': 'فاخر',
    'stats.customers': 'عملاء سعداء',
    'stats.products': 'منتجات فاخرة',
    'stats.cities': 'مدن مخدومة',
    'stats.years': 'سنوات من الثقة'
  }
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

function getInitialLanguage(): LanguageCode {
  if (typeof window === 'undefined') return 'en';
  try {
    const saved = localStorage.getItem(STORAGE_KEY);
    if (saved === 'en' || saved === 'ur' || saved === 'ar') {
      return saved;
    }
  } catch {
    // localStorage restricted in certain private modes
  }
  return 'en';
}

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>(getInitialLanguage);

  const isRtl = useMemo(() => language === 'ur' || language === 'ar', [language]);

  const setLanguage = useCallback((lang: LanguageCode) => {
    setLanguageState(lang);
    try {
      localStorage.setItem(STORAGE_KEY, lang);
    } catch {
      // ignore
    }
  }, []);

  // Update document attributes without remounting or breaking existing state
  useEffect(() => {
    if (typeof document === 'undefined') return;
    document.documentElement.lang = language;
    document.documentElement.dir = isRtl ? 'rtl' : 'ltr';
    if (isRtl) {
      document.documentElement.classList.add('rtl');
    } else {
      document.documentElement.classList.remove('rtl');
    }
  }, [language, isRtl]);

  const t = useCallback((key: string, defaultText = ''): string => {
    return TRANSLATIONS[language]?.[key] || TRANSLATIONS.en[key] || defaultText || key;
  }, [language]);

  const value = useMemo(() => ({
    language,
    isRtl,
    setLanguage,
    t
  }), [language, isRtl, setLanguage, t]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export function useLanguage(): LanguageContextValue {
  const context = useContext(LanguageContext);
  if (!context) {
    return {
      language: 'en',
      isRtl: false,
      setLanguage: () => {},
      t: (key: string, defaultText = '') => defaultText || key
    };
  }
  return context;
}
